select
    'Washington 211' as contributor,
    agency_id as organization_id,
    service_id as id,
    servicesystem_dateoflastcompleteupdate as assured_date,
    serviceoption_status as status,
    servicesystem_name as name,
    servicecustom_wa211serviceaffectedbycovid19 as emergency_information,
    servicesystem_description as short_description,
    servicesystem_phonemain as phone_number,
    servicecustom_phone1ext as phone_extension,
    servicecustom_phone1description as phone_description,
    servicesystem_emailaddress as email,
    servicesystem_websiteurl as url,
    (regexp_matches(serviceprogram_serviceprogram, '(\d+)'))[1] as program_id,
    servicesite_servicesite as service_at_location,
    servicehoursofoperation_modulehoursofoperation as schedule_module,
    servicesystem_hoursofoperation as schedule_description,
    servicetaxonomy_moduleservicepost as taxonomy_term,
    servicegeotagus_servicegeotagus as extent,
    servicecustom_serviceaka as alternate_name,
    serviceoption_focuspopulations as focus_population,
    serviceoption_agegroups as age_group,
    serviceoption_disabilitieshealthconditions as health_condition
from {{ ref('src_wa_service') }}