version: 2

sources:
  - name: silobuster_dbt
    database: defaultdb
    schema: public
    tables:
      - name: wa211_agency
      - name: wa211_program
      - name: wa211_service
      - name: wa211_site
      - name: within_contact
      - name: within_language
      - name: within_location
      - name: within_organization
      - name: within_payment_accepted
      - name: within_phone
      - name: within_physical_addresse
      - name: within_required_document
      - name: within_schedule
      - name: within_service
      - name: within_service_area
      - name: within_service_attribute
      - name: within_taxonomy_term
      - name: what_contact
      - name: what_location
      - name: what_organization
      - name: what_phone
      - name: what_physical_addresse
      - name: what_schedule
      - name: what_service
      - name: what_taxonomy_term